# -*- coding: utf-8 -*-

from sqlalchemy import (Table,
                        Column,
                        Integer,
                        Text,
                        Sequence,
                        func,
                        DateTime,
                        Float,
                        Boolean,
                        ForeignKey)

def getDemandeIntervention(metadata):
    autoload = False
    if metadata.bind.has_table('demande_intervention'):
        autoload = True
    return Table('demande_intervention', metadata,
                 Column('di_pk', Integer(),
                        Sequence('demande_intervention_di_pk_seq'),
                        primary_key=True),
                 Column('di_date_creation', DateTime(), default=func.now()),
                 Column('di_nom_demandeur', Text()),
                 Column('di_prenom_demandeur', Text()),
                 Column('di_gsm_demandeur', Text()),
                 Column('di_email_demandeur', Text()),
                 Column('di_nom_demandeur', Text()),
                 Column('di_rue_demandeur', Text()),
                 Column('di_cp_demandeur', Text()),
                 Column('di_localite_demandeur', Text()),
                 Column('di_nom_non_locataire', Text()),
                 Column('di_prenom_non_locataire', Text()),
                 Column('di_gsm_non_locataire', Text()),
                 Column('di_email_non_locataire', Text()),
                 Column('di_rue_non_locataire', Text()),
                 Column('di_cp_non_locataire', Text()),
                 Column('di_localite_non_locataire', Text()),
                 Column('di_probleme_electrique_demandeur', Text()),
                 Column('di_probleme_plomberie_demandeur', Text()),
                 Column('di_probleme_menuiserie_demandeur', Text()),
                 Column('di_probleme_toiture_demandeur', Text()),
                 Column('di_probleme_chauffage_demandeur', Text()),
                 Column('di_type_chauffage_demandeur', Text()),
                 Column('di_probleme_eau_chaude_demandeur', Text()),
                 Column('di_probleme_chauffage_demandeur', Text()),
                 Column('di_probleme_wc_evacuation_demandeur', Text()),
                 Column('di_deboucher_wc_demandeur', Boolean()),
                 Column('di_probleme_horticol_demandeur', Text()),
                 Column('di_probleme_humidite_demandeur', Text()),
                 Column('di_probleme_autre_motif_demandeur', Text()),
                 Column('di_commentaire_ipplf', Text()),
                 Column('di_etat_ipplf', Boolean()),
                 autoload=autoload,
                 extend_existing=True)